
package:
	~/.local/apache-maven-3.2.5/bin/mvn package

deps:
	~/.local/apache-maven-3.2.5/bin/mvn dependency:copy-dependencies

test:
	CLASSPATH=target/classes:target/batch-jython-1.0-SNAPSHOT.jar:src/main/resources/log4j.xml:src/main/resources/:/mnt/data/home/mdupont/experiments/java/jython/dist/Lib/site-packages:target/dependency/mockito-core-1.9.5.jar:target/dependency/postgresql-9.4-1200-jdbc41.jar:target/dependency/commons-logging-1.1.jar:target/dependency/spring-boot-starter-test-1.0.2.RELEASE.jar:target/dependency/spring-boot-1.0.2.RELEASE.jar:target/dependency/hsqldb-2.3.2.jar:target/dependency/logkit-1.0.1.jar:target/dependency/spring-retry-1.1.0.RELEASE.jar:target/dependency/jul-to-slf4j-1.7.7.jar:target/dependency/com.ibm.jbatch-tck-spi-1.0.jar:target/dependency/logback-core-1.1.2.jar:target/dependency/xpp3_min-1.1.4c.jar:target/dependency/spring-aop-4.0.3.RELEASE.jar:target/dependency/jcl-over-slf4j-1.7.7.jar:target/dependency/junit-4.11.jar:target/dependency/spring-boot-autoconfigure-1.0.2.RELEASE.jar:target/dependency/log4j-1.2.17.jar:target/dependency/snakeyaml-1.13.jar:target/dependency/slf4j-api-1.7.7.jar:target/dependency/spring-expression-4.0.3.RELEASE.jar:target/dependency/jna-4.1.0.jar:target/dependency/spring-core-4.1.4.RELEASE.jar:target/dependency/aopalliance-1.0.jar:target/dependency/spring-context-4.0.3.RELEASE.jar:target/dependency/spring-batch-core-3.0.3.RELEASE.jar:target/dependency/spring-boot-starter-1.0.2.RELEASE.jar:target/dependency/objenesis-1.0.jar:target/dependency/jettison-1.2.jar:target/dependency/slf4j-simple-1.7.7.jar:target/dependency/javax.batch-api-1.0.1-b01.jar:target/dependency/spring-dao-2.0.8.jar:target/dependency/spring-boot-starter-logging-1.0.2.RELEASE.jar:target/dependency/hamcrest-library-1.3.jar:target/dependency/jna-platform-4.1.0.jar:target/dependency/spring-integration-core-3.0.2.RELEASE.jar:target/dependency/waffle-jna-1.7.jar:target/dependency/xstream-1.4.7.jar:target/dependency/spring-messaging-4.0.3.RELEASE.jar:target/dependency/xmlpull-1.1.3.1.jar:target/dependency/spring-boot-starter-batch-1.0.2.RELEASE.jar:target/dependency/spring-jdbc-4.1.4.RELEASE.jar:target/dependency/logback-classic-1.1.2.jar:target/dependency/spring-test-4.0.3.RELEASE.jar:target/dependency/spring-batch-infrastructure-3.0.3.RELEASE.jar:target/dependency/jython-2.7-b3.jar:target/dependency/servlet-api-2.3.jar:target/dependency/avalon-framework-4.1.3.jar:target/dependency/hamcrest-core-1.3.jar:target/dependency/spring-tx-4.0.3.RELEASE.jar:target/dependency/guava-18.0.jar:target/dependency/spring-data-commons-1.9.2.RELEASE.jar:target/dependency/log4j-over-slf4j-1.7.7.jar:target/dependency/spring-beans-4.1.4.RELEASE.jar /mnt/data/home/mdupont/experiments/java/jython/dist/bin/jython ./src/main/python/test_import.py
