package us.thefr33.batch;

import java.util.List;
import java.util.Arrays;
/**
 * generated by UnSprung
 * http://code.google.com/p/unsprung/
see https://github.com/cbushell/spring-batch-play/blob/49a85c4d6d52d9cbc2a074f514db467f2398a5ba/src/main/java/foo/bar/baz/SimpleBatchFlow.java
 */
public class MySpringContext {

	private org.springframework.batch.core.job.SimpleJob bean_simpleJob;	// /mnt/data/home/mdupont/experiments/java/batch-jython/src/main/resources/simple.xml
	us.thefr33.batch.PythonTasklet bean_hello;	// /mnt/data/home/mdupont/experiments/java/batch-jython/src/main/resources/simple.xml


	public MySpringContext(
                             org.springframework.batch.core.repository.JobRepository 
                             bean_jobRepository,
                             org.springframework.transaction.PlatformTransactionManager bean_transactionManager
                             ) 
    {
        
        try {

                    org.springframework.batch.core.launch.support.SimpleJobLauncher bean_jobLauncher;	// /mnt/data/home/mdupont/experiments/java/batch-jython/src/main/resources/applicationContext.xml
                    org.springframework.batch.core.step.tasklet.TaskletStep bean_taskletStep;	// /mnt/data/home/mdupont/experiments/java/batch-jython/src/main/resources/simple.xml
                    //bean_jobRepository = new org.springframework.batch.core.repository.support.SimpleJobRepository( );
			setBean_simpleJob(new org.springframework.batch.core.job.SimpleJob( ));
			getBean_simpleJob().setJobRepository( bean_jobRepository );

			getBean_simpleJob().setName( "simpleJob" );


			bean_hello = new us.thefr33.batch.PythonTasklet( );
			bean_jobLauncher = new org.springframework.batch.core.launch.support.SimpleJobLauncher( );
			bean_jobLauncher.setJobRepository( bean_jobRepository );

                        
			bean_taskletStep = new org.springframework.batch.core.step.tasklet.TaskletStep( );
			bean_taskletStep.setJobRepository( bean_jobRepository );
			bean_taskletStep.setTransactionManager( bean_transactionManager );
                        bean_taskletStep.setTasklet( bean_hello );


                        List<org.springframework.batch.core.Step> steps = Arrays.asList(
                                                                                        new org.springframework.batch.core.Step[] 
                                                         { bean_taskletStep });

                        getBean_simpleJob().setSteps(steps);


		} catch(Throwable t) {
			t.printStackTrace();
		}

	}


	org.springframework.batch.core.job.SimpleJob getBean_simpleJob() {
		return bean_simpleJob;
	}


	void setBean_simpleJob(org.springframework.batch.core.job.SimpleJob bean_simpleJob) {
		this.bean_simpleJob = bean_simpleJob;
	}
}
